import { ENERGY_NEWS_CONFIG } from '@/data/energy-news-config';
import { slugifyHeadline } from './normalizeArticle';
import type { ScoredCandidate } from './types';

function yamlList(values: string[]) {
  if (values.length === 0) return '[]';
  return `\n${values.map((value) => `  - ${value}`).join('\n')}`;
}

function isoDate(value: Date | null) {
  return (value ?? new Date()).toISOString().slice(0, 10);
}

/**
 * Draft markdown for editorial review. Summaries are placeholders — never publish without an original write-up.
 */
export function candidateToDraftMarkdown(candidate: ScoredCandidate) {
  const slug = slugifyHeadline(candidate.title);
  const pubDate = isoDate(candidate.publishedAt);
  const body = `---
title: ${JSON.stringify(candidate.title)}
description: ${JSON.stringify(candidate.description.slice(0, 160) || 'Editorial summary required before publication.')}
pubDate: ${pubDate}
sourceDate: ${pubDate}
draft: true
indexable: false
featured: false
archived: false
contentType: ${candidate.suggestedType}
region: ${candidate.suggestedRegion}
categories: ${yamlList(candidate.suggestedCategories)}
tags: ${yamlList(candidate.tags)}
sourceId: ${candidate.sourceId}
sourceName: ${JSON.stringify(candidate.sourceName)}
sourceUrl: ${JSON.stringify(candidate.url)}
originalUrl: ${JSON.stringify(candidate.url)}
summary: "Replace this with an original 2–4 sentence explanation of what happened. Do not paste the source article."
whyItMatters: "Replace this with original commentary on why the development matters to the power sector."
perspective: "Optional professional context. Do not invent an official company position."
---

This file was generated by ingest and is **not approved**.

- Relevance score: ${candidate.relevanceScore}
- Source: ${candidate.sourceName}
- Original URL: ${candidate.url}

Write an original editorial summary before setting \`draft: false\` and \`indexable: true\`.
Do not copy article text. Minimum summary length: ${ENERGY_NEWS_CONFIG.copyright.minSummaryChars} characters.
`;

  return { slug, markdown: body };
}
